### ISSUE TITLE
Raspberry Pi error: numpy.ndarray size changed

### ISSUE THREAD

**Issue by ssinfod** [rybodiddly/Kijiji-Reposter#24]
I tried to install Kijiji-Reposter on a Raspberry Pi.

I get the following error when I start the program: 
`ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 44 from C header, got 40 from PyObject
`

Details:
```
pi@raspberrypi:~/Kijiji-Reposter $ python server.py
Traceback (most recent call last):
  File "/home/pi/Kijiji-Reposter/server.py", line 5, in <module>
    import pgeocode
  File "/home/pi/.local/lib/python3.9/site-packages/pgeocode.py", line 14, in <module>
    import pandas as pd
  File "/home/pi/.local/lib/python3.9/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import (
  File "/home/pi/.local/lib/python3.9/site-packages/pandas/compat/__init__.py", line 15, in <module>
    from pandas.compat.numpy import (
  File "/home/pi/.local/lib/python3.9/site-packages/pandas/compat/numpy/__init__.py", line 7, in <module>
    from pandas.util.version import Version
  File "/home/pi/.local/lib/python3.9/site-packages/pandas/util/__init__.py", line 1, in <module>
    from pandas.util._decorators import (  # noqa
  File "/home/pi/.local/lib/python3.9/site-packages/pandas/util/_decorators.py", line 14, in <module>
    from pandas._libs.properties import cache_readonly  # noqa
  File "/home/pi/.local/lib/python3.9/site-packages/pandas/_libs/__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 44 from C header, got 40 from PyObject
pi@raspberrypi:~/Kijiji-Reposter $
```

I suppose that the Raspberry Pi was probably not a 'target device'. I just want to report the problem in case a simple/quick fix exists...
It is probably related to processor architecture (32 bits versus 64 bits).

**Comment by rybodiddly** [comment]
This issue is related to `pandas` usage of `numpy`. Both are dependencies of `pgeocode`. This issue is beyond the scope of the kijiji-reposter. Your best bet is to check with the devs of [pgeocode](https://github.com/symerio/pgeocode) and open an issue there to see if they have a raspberry pi compatible build.
