### ISSUE TITLE
AutoReplier raised an exception

### ISSUE THREAD

**Issue by jaipanc** [rybodiddly/Kijiji-Reposter#29]
```
Job "messageAutoReplier (trigger: cron[minute='*/1'], next run at: 2022-08-31 09:39:00 EDT)" raised an exception
Traceback (most recent call last):
  File "C:\Users\Vostro\AppData\Local\Programs\Python\Python310\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "C:\Users\Vostro\Desktop\UI-Reposter\server.py", line 398, in messageAutoReplier
    conversationID = item['@uid']
TypeError: string indices must be integers
```

**Comment by rybodiddly** [comment]
what's the api message returned by kijiji?
