### ISSUE TITLE
on posting ads 

### ISSUE THREAD

**Issue by stanlyong** [rybodiddly/Kijiji-Reposter#30]
TypeError
TypeError: 'NoneType' object is not subscriptable

Traceback (most recent call last)
File "d:\Code\kjjreposter\venv\lib\site-packages\flask\app.py", line 2548, in __call__
return self.wsgi_app(environ, start_response)
File "d:\Code\kjjreposter\venv\lib\site-packages\flask\app.py", line 2528, in wsgi_app
response = self.handle_exception(e)
File "d:\Code\kjjreposter\venv\lib\site-packages\flask\app.py", line 2525, in wsgi_app
response = self.full_dispatch_request()
File "d:\Code\kjjreposter\venv\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
rv = self.handle_user_exception(e)
File "d:\Code\kjjreposter\venv\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
rv = self.dispatch_request()
File "d:\Code\kjjreposter\venv\lib\site-packages\flask\app.py", line 1796, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
File "d:\Code\kjjreposter\Kijiji-Reposter\server.py", line 978, in submit
adID = parsed['ad:ad']['@id']
TypeError: 'NoneType' object is not subscriptable
The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.
To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it. For code execution mouse-over the frame you want to debug and click on the console icon on the right side.

You can execute arbitrary Python code in the stack frames and there are some extra helpers available for introspection:

dump() shows all variables in the frame
dump(obj) dumps all that's known about the object

**Comment by stanlyong** [comment]
Please excuse me if anything obvious, not a big developer here

**Comment by adibf933** [comment]
were you able to fix it?
